### ISSUE TITLE
Should make it clear that this doesn't work with code reloading in development

### ISSUE THREAD

**Issue by scomma** [rails/cache_digests#13]
It wasn't until I inspect the source of `CacheDigests::TemplateDigestor` that I realized the digests themselves are only compute once and cached in a MemoryStore.

It would be nice if cache_digests could detect if class caching is disabled in Rails, then disable this caching of digests, following the principle of least surprise.

**Comment by scomma** [comment]
If maintainers approve of the idea I'll work on a pull request.

**Comment by dhh** [comment]
Caching classes doesn't really have anything to do with this, though.

How is this a problem for you?

**Comment by scomma** [comment]
I'm working on an app which will employ russian-doll caching heavily, and I'd like to have `perform_caching` enabled in development to make sure fragments get rendered/cached correctly.

**Comment by HaloZero** [comment]
I'm with @scomma on this, it would be nice to know this since I wanted to test how well it works before I deploy it. assuming that this is the reason why it doesn't work in development mode.

**Comment by dhh** [comment]
We should have a dedicated setting, then.

**Comment by scomma** [comment]
Ok, working on a patch.
