### ISSUE TITLE
How to use it with cache sweeper?

### ISSUE THREAD

**Issue by phuongnd08** [rails/cache_digests#14]
If I want to invalidate a cache when a model is created, how would I do it?

**Comment by dhh** [comment]
Call #touch on whatever you've made that cache depend on. See key-based expiration.

**Comment by phuongnd08** [comment]
Okay, I guess my case is a little special:
So I make a cache like this:

```
- cache 'testimonials' do
  = render 'testimonials', :testimonials => Testimonial.approved
```

We implemented a sweeper to make a call to expire_fragment('testimonial') when a testimonial is changed. But as far as I tried, expire_fragment doesn't work (because the cache key 'testimonial/<digest>'?)

**Comment by dhh** [comment]
Cache digests is not intended to work with manual expiration using a sweeper. Only key-based expiration.

**Comment by phuongnd08** [comment]
Are you saying expire_fragment work without cache_digests but won't work with cache_digests?

**Comment by dhh** [comment]
Correct. They are not designed to work together. Cache digests are only intended to work together with key-based expiration where you never need to manually expire and know the whole cache key.

There's a pull request available for turning off the digest on a per-call basis pending, though.
