### ISSUE TITLE
Cache is not being invalidated

### ISSUE THREAD

**Issue by phuongnd08** [rails/cache_digests#15]
Inside a page, I cache its fragment like this:
- cache 'testimonials' do
  = render "template_name"

When I change template_name content, the cache is not being invalidated (its content is not re-rendered).

**Comment by phuongnd08** [comment]
Oh, look like it won't work during development mode because the digest is calculated only once

**Comment by BlakeWilliams** [comment]
Sounds broken to me.

**Comment by fgrehm** [comment]
Join us at #11 :-)
