### ISSUE TITLE
Request: cache semi-static pages?

### ISSUE THREAD

**Issue by hayksaakian** [rails/cache_digests#29]
Maybe I'm too new at this, but is there any way this could be used to cache static pages generated with embedded ruby (html.erb)?

example: I have some marketing pages with embedded ruby in my InfoController. 

An about us page, tutorial page, a downloads page, and these will only ever change between code updates.

I'm not sure how to implement this, or if cache digests are even the correct way to do it.

something like

```
# in InfoController#about
<% cache %>
    <h1>About</h1>
    <p>This is a Software as a Service web application</p>
    <%= link_to 'learn how to use the software', tutorial_path %>
<% end %>
```

**Comment by dhh** [comment]
Yup, that'll work! Cache will be busted when you change the content. But of all you are doing is what you show below, it's not really worth it. The goal is to save on computation. No real computation is needed for that block.

**Comment by hayksaakian** [comment]
I know how to do this now. (cleaning up my old issues at the moment)
