### ISSUE TITLE
Issues with dynamic partial names

### ISSUE THREAD

**Issue by firedev** [rails/cache_digests#31]
I have something like this:

```
<% cache [object] do %>
  <%= render partial: "item_features_#{object.profile}", locals: { object: object } %>
 ...
<% end %>
```

And in logs I see this from time to time:

`Couldn't find template for digesting: objects/item_features_.html`

Maybe I am doing it wrong, and should just cache `item_features_*` instead?

**Comment by dhh** [comment]
You have to explicitly state the dependencies in that case. See the docs on explicit deps and ignore the log line.

**Comment by firedev** [comment]
Sorry, but I have tried to add template dependencies like this before `render`:

```
<%# Template Dependency: objects/item_features_rent %>
<%# Template Dependency: objects/item_features_sale %>
```

But it says that it can't find the template anyway. Guess I will have to ignore it.

**Comment by dhh** [comment]
Right, then it's all good! Just ignore the logging.

**Comment by firedev** [comment]
I still think this is somewhat untidy. Besides it goes against everything I know. If you see warnings in logs - fix them.

**Comment by marcusg** [comment]
@firedev Have you found a way to fix the warnings in logs?

**Comment by firedev** [comment]
Nope, just ignored it.

**Comment by maxgronlund** [comment]
The whole idea about caching is speed improvement, logging 'non errors ' is a drawback in that direction and noise for the developers that have to know 'oh that warning just ignore it'

**Comment by mahemoff** [comment]
+1 Habitually ignoring errors in log messages is not a good practice.

**Comment by jwaldrip** [comment]
+1 Agreed

**Comment by bolshakov** [comment]
Instead ignoring log messages you may stop logging at all

**Comment by pelargir** [comment]
+1 for a fix
