### ISSUE TITLE
Using cache_digests with cache("custom_name") not working

### ISSUE THREAD

**Issue by tomaswitek** [rails/cache_digests#35]
```
<% cache "menu" do %>
    bla bla...
<% end %>
```

I'm manually invalidating this cache by (it's working okay without cache_digests):

```
expire_fragment("menu")
```

Without cache_digests I'm getting this log:

```
Read fragment views/menu
```

After bundling cache_digests I'm getting this:

```
Read fragment views/menu/0fe212b51fb84adbcc47ef7e93bef477
```

Hash added after this fragment causes that I can't manually invalidate expire_fragment("menu").

**Comment by dhh** [comment]
Cache digests is not designed to be manually expired. The cache will simply stop being used when the key changes. See http://37signals.com/svn/posts/3113-how-key-based-cache-expiration-works.

**Comment by tomaswitek** [comment]
Thanks for quick reply. I know how it works, but there is no possibility to use these two types of invalidation separately in one application?

**Comment by dhh** [comment]
Not like this, no. What you can do to have a similar effect is make a timestamp part of the key that you'll manually bump to signify the expiration.
