### ISSUE TITLE
belongs_to association not touching correctly

### ISSUE THREAD

**Issue by caarlos0** [rails/cache_digests#38]
Let's say I have a model like:

```
class Person < ActiveRecord::Base
  # content...
end
```

and another:

```
class Bike < ActiveRecord::Base
  belongs_to :person, touch: true
end
```

If I change any attribute of bike, the person should be touched. That's ok.

The things is: if I change the Bike Person from `Joao` to `Maria`, only `Maria` is touched, while `Joao` are not.

Is that a bug, or I have to do something about it?

Thanks in advance.

**Comment by jeremy** [comment]
Good catch! Could you file a pull request in Rails for this? Changing an association should touch the old associate.

**Comment by caarlos0** [comment]
OK, I'll try.

By now, if someone else have this issue, I fixed it with this:

```
  before_update {
    if self.person_id_changed?
      Bike.find(self.id).person.touch
    end
  }
```

Cheers
