### ISSUE TITLE
'stack level too deep' with recursive partial

### ISSUE THREAD

**Issue by gmcnaughton** [rails/cache_digests#39]
I have a partial that recursively renders a nested list of comments.  When I try to run `rake cache_digests:nested_dependencies` on it, rake fails with `stack level too deep`.

Using ruby-1.9.3-p194, rails 3.2.13, and cache_digests 0.2.0:

``` erb
<%# app/views/comments/_comment.html.erb
<%= comment.text %>
<% if comment.replies.count > 0 %>
  <% comment.replies.each do |reply| %>
    <%= render :partial => "comments/comment", :locals => { :comment => reply } %>
  <% end %>
<% end %>
```

When I try to analyze it:

```
$ rake cache_digests:nested_dependencies TEMPLATE=comments/_comment
rake aborted!
stack level too deep
```

Any thoughts?  Is it possible that this is just a problem with the nested_dependencies rake task, and wouldn't cause issues in production?  (I haven't deployed yet because I wanted to double-check the dependency graph first...)

**Comment by gmcnaughton** [comment]
Unfortunately it looks like this breaks the server, not just the rake task.  Trying to hit a page with a fragment cache wrapped around the recursive partial crashes WEBrick with `Illegal instruction: 4` (WEBrick 1.3.1, OSX Mountain Lion 10.8.3)

**Comment by buffym** [comment]
I just ran into this issue too, and noticed it has been fixed in master, but the gem version  hasn't been bumped yet. If you uninstall your cache_digests gem and reinstall from git, it should fix it. It appears to have been fixed in #10

**Comment by gmcnaughton** [comment]
Oops, I didn't think to check!  Thanks for the tip!

**Comment by dhh** [comment]
Pushed new 0.3.0 version.

**Comment by yob** [comment]
Is this fixed in rails4 too?

We also have a comments partial that renders itself recursively and I'm seeing a similar error while trying to upgrade our app from rails v3.2.13 to v4.0.0
