### ISSUE TITLE
Changes to helpers don’t bust the cache

### ISSUE THREAD

**Issue by codyrobbins** [rails/cache_digests#4]
Skimming through the code it looks like if a template calls a helper; and the helper is changed; then the digest for the cache won’t change and the cache won’t be busted. If this is indeed the case it’s something to be aware of and I think it should be mentioned in the readme. I’m happy to make the change.

**Comment by dhh** [comment]
That is indeed the case. I've documented things when this got merged into Rails:
https://github.com/rails/rails/blob/502d5e24e28b3634910495d0fb71cb20b1426aee/actionpack/lib/action_view/helpers/cache_helper.rb

On Sep 25, 2012, at 11:37 AM, Cody Robbins wrote:

> Skimming through the code it looks like if a template calls a helper; and the helper is changed; then the digest for the cache won’t change and the cache won’t be busted. If this is indeed the case it’s something to be aware of and I think it should be mentioned in the readme. I’m happy to make the change.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

David Heinemeier Hansson

**Comment by codyrobbins** [comment]
Missed that—thanks!
