### ISSUE TITLE
Not detecting correct partial for model.association

### ISSUE THREAD

**Issue by calebhearth** [rails/cache_digests#50]
I believe that cache_digests is not picking up the correct partial:

app/views/feed_statuses/_feed_status.html.erb

``` erb
<% cache feed_status do %>
  <header>
    <%= render feed_status.user %>
    <%= timestamp(feed_status.created_at) %>
  </header>

  <section>
    <p><%= auto_link(feed_status.body) %></p>
  </section>
<% end %>
```

 rake cache_digests:nested_dependencies TEMPLATE=feed_statuses/_feed_status

``` json
[
  "feed_statuses/feed_status.user"
]
```

Based on the README, which states that `render(message.topics) => render("topics/topic")`, I would expect this to understand the singular association as well. Is that not correct?

expected:

``` json
[
  "users/user"
]
```

**Comment by latortuga** [comment]
Good find, I just reproduced this as a regex issue, I'll submit a PR to fix it soonish.
