### ISSUE TITLE
Release to RubyGems?

### ISSUE THREAD

**Issue by fgrehm** [rails/cache_digests#52]
When [I used](https://github.com/rails/cache_digests/pull/24) cache_digests on my last project I had to do what is now being done automatically after https://github.com/rails/cache_digests/pull/48. Now that I came back after almost 6 months and I saw the notice on the README I thought that things would just work but it didn't. After some debugging I found out that that code has not been released yet :-P

Would anyone be able to push a new version to rubygems? I'm referencing the github project on my Gemfile but would be awesome to use a released version.

Thanks a lot in advance :-)

**Comment by sadjow** [comment]
+1

**Comment by dhh** [comment]
0.3.1 released.

**Comment by fgrehm** [comment]
@dhh Thanks!
