### ISSUE TITLE
Calling cache([object]) and cache(object) Using the Same Key

### ISSUE THREAD

**Issue by ksylvest** [rails/cache_digests#53]
It appears cache keys are identical for an `ActiveRecord::Base` and `ActiveRecord::Relation` if the `ActiveRecord::Relation` is the single `ActiveRecord::Base` object. For example:

```
Person.create(name: "Kevin")

@person = Person.find_by(name: "Kevin") # <Person name: "Kevin">
@people = Person.where(name: "Kevin") # <ActiveRecord::Relation [<Person name: "Kevin">]>

@person.to_json # { name: "Kevin" }
@people.to_json # [{ name: "Kevin" }]
```

This causes a bug with the following snippet:

```
<% # _json.html.erb %>
<% cache object do %>
<%= object.to_json %>
<% end %>
```

Results:

```
<% # random.html.erb %>
<%= render 'json', object: @people %> # [{ name: "Kevin" }]
<%= render 'json', object: @person %> # [{ name: "Kevin" }]
```

Note: the last two lines result in the same JSON although the second should **not** be nested inside an array.

**Comment by dhh** [comment]
Why is that a problem? Why shouldn't the cache be shared between "1" and ["1"]?

**Comment by ksylvest** [comment]
@dhh Thanks for getting back. My thought is that the keys should be different because `ActiveRecord::Base` and `ActiveRecord::Relation` are completely different and won't return consistent results for any of the `to_json`, `to_xml`, etc methods. 

I ran into an issue trying to cache a partial used to render either a Backbone model or collection into the DOM on page load. I fixed it by using two different partials for the relation versus base, however it wasn't clear this is desired behavior.

**Comment by dhh** [comment]
Cache digests includes the path of the partial in the cache key. So you can use "cache @model" in two different partials without a collision.

**Comment by ksylvest** [comment]
@dhh Thanks. I ran into a collision because I was using the the same partial (maybe a bad idea? the code was the same for both in my case). Closing.

**Comment by dhh** [comment]
If it's the same partial, I don't understand why the output would be different between [1] and "1"? If the output is different, then different partials sounds like the way to go.
