### ISSUE TITLE
The generated keys of item and items which size is 1 are the same

### ISSUE THREAD

**Issue by aikko** [rails/cache_digests#54]
like this
the generated key of the item show is views/shows/28608-20130704070313/53b57e0d52d1d769538e3a7b94a81cae

the generated key of  item array shows which only contain the item show above-mentioned is views/shows/28608-20130704070313/53b57e0d52d1d769538e3a7b94a81cae too

is this a bug?

``` javascript
<% cache @shows do %>
       ***
     <% @shows.each do |show| %>
            <% cache(show) do %>
                    ***
            <% end %>
     <% end %>
      ***
<% end%>
```

when the shows's size is 1, it's wrong.

**Comment by Osseta** [comment]
This is discussed in https://github.com/rails/cache_digests/issues/53

**Comment by aikko** [comment]
Thanks
