### ISSUE TITLE
Missing rake tasks in Rails 4

### ISSUE THREAD

**Issue by tvdeyen** [rails/cache_digests#58]
This gem offers great rake tasks:

``` bash
rake cache_digests:dependencies 
rake cache_digests:nested_dependencies
```

Although `cache_digests` was merged into Rails 4, the rake tasks weren't?

Is there any reason for this?

**Comment by dhh** [comment]
No, I'd like to have these tasks in Rails 4 as well. Please extract and prepare a PR for Rails.

**Comment by tvdeyen** [comment]
Done

**Comment by rafaelfranca** [comment]
Merged in 4-0-stable

**Comment by tvdeyen** [comment]
Woot! That was fast :heart:
