### ISSUE TITLE
Overwrite cache content with dynamic parts

### ISSUE THREAD

**Issue by amnesia7** [rails/cache_digests#66]
I have a partial that contains a section of code in a `cache project do` block as normal.

Within the code of the partial I output a snippet of the project description - first 100 characters using `truncate` - which is fine when just listing projects.

However, if the user performs a search of projects and the search term is contained in the project description then when I ouput the description snippet as part of the partial I would like to replace the basic snippet with a snippet that relates to the search term (eg 10 words either side of the search term using `excerpt`).

I can do this replacement using javascript (setting the dynamic description as a `data` attribute on the div container and using it to overwrite the description text) after loading the cached html but I was wondering if it is possible to replace parts of the cached html using rails before outputting it out to the screen removing the need for it to be done using javascript (which could otherwise cause a flash of the basic description before overwriting it).

I thought about using two `cache` blocks in the partial (one either side of the description) but I've just hit another part of the partial that I would like to be dynamic as well and was wondering if it was possible to pass the output of `cache project do` into a replace function or something that replaces part of the html with the dynamic part somehow and then outputs the html.

There are still enough parts of my partial to warrant it being cached.

**Comment by amnesia7** [comment]
I think it's something along the lines of what @teeparham has done with https://github.com/neighborland/cache_rocket although I'm unsure if I can use it yet because it mentions a dependency of rake `~> 10.3` and I'm limited to `~> 0.9.6`. but I am on ruby 2.0 rails 4.1. 
Unless there's a way to do this using normal rails caching then I guess I'll have to checkout cache_rocket out and see if that can do what I'm after.

**Comment by teeparham** [comment]
@amnesia7 Yes, those are the two ways to the replacement: client-side javascript or server-side with `cache_rocket` (or similar). The rake dependency in `cache_rocket` is only a development dependency - there is no runtime dependency.

**Comment by amnesia7** [comment]
Thanks @teeparham I'll have to give it a whirl then
