### ISSUE TITLE
Does this work with haml?

### ISSUE THREAD

**Issue by mb-dev** [rails/cache_digests#8]
I am having trouble getting this to work. I update the partial but the caching is still not refreshing. 

Let me know if this is compatible with haml and i'll post some code snippets.

**Comment by dhh** [comment]
This has not been tested with haml, so if its not working, it'll need someone who cares to work on that to look into it.

**Comment by pokonski** [comment]
@ddh was it tested with ERB only? Because I'm willing to take a look into HAML/Slim issues.

**Comment by Arjeno** [comment]
I can confirm it's working with Slim. Although not in development mode.

**Comment by dhh** [comment]
Yes, and jbuilder. Please do investigate.

**Comment by azul** [comment]
Does not seem to work with haml for me either. Adding content in the template that has the cache line will not expire the cache in development.

**Comment by ready4god2513** [comment]
Do we have any movement on this?  If not, it is something that I would be interested in looking in to.

**Comment by dhh** [comment]
I haven't heard of any. Have at it!

**Comment by dasch** [comment]
Could the dependency tracking be moved to the template handlers, perchance? That way, each handler could go about it its own way.

**Comment by balexand** [comment]
I'm using cache_digests with HAML and the only issue I can find is fixed in #21. I also created tests in #22. I included the tests separately, since I'm not sure if @dhh will want the added complexity in the test suite. This issue can be closed after #21 is merged.

**Comment by balexand** [comment]
This issue can be closed now that #34 has been merged. /cc @rafaelfranca

**Comment by rafaelfranca** [comment]
Yes. Thank you

**Comment by phuongnd08** [comment]
I'm using `cache_digests (0.3.1)` with haml right now and `rake  cache_digests:dependencies` still returns empty array all the time. I even put this in initializer: `CacheDigests::DependencyTracker.register_tracker :haml, CacheDigests::DependencyTracker::ERBTracker`.

**Comment by azul** [comment]
@phuongnd08 same thing here. Have you been able to fix it?

**Comment by phuongnd08** [comment]
I switched over to AngularJS a while back so we no longer need html fragment caching.

**Comment by azul** [comment]
Turns out i still lacked the initializer and with the initializer it works for me now.
Thanks for the quick reply never the less, @phuongnd08. :smile:

**Comment by jjb** [comment]
as of https://github.com/indirect/haml-rails/pull/51/, haml-rails will automagically do this
