### ISSUE TITLE
I18n.t inside partial

### ISSUE THREAD

**Issue by kalys** [rails/cache_digests#9]
Let's assume that we have partial like below:

```
<% cache @post do %>
  <%= t(:post_created_at) %> <%= @post.created_at %>
<% end %>
```

Caching doesn't know about locales and it won't replace cache if locale is changed.

The following code works.

```
<% cache [I18n.locale, @post] do %>
  <%= t(:post_created_at) %> <%= @post.created_at %>
<% end %>
```

Will caching implicitly depend on I18n.locale in future versions?

**Comment by dhh** [comment]
Probably not. Putting the local in there or wrapping the cache call in local_cache sounds like the way to go.

**Comment by kalys** [comment]
Thank you.

**Comment by pekeler** [comment]
Your suggestion solves changing the locale, but what if I change the translation for :post_created_at?
http://stackoverflow.com/questions/11055056/how-can-the-cache-for-the-views-with-translations-be-invalidated has an interesting solution. However, figuring out the scopes for deeply nested views is a hassle and seems like it would duplicate the work that cache_digest does anyways (finding sub-views). So I think it would make a lot of sense if cache_digest was i18n-aware.
